from datetime import timedelta
from decimal import Decimal

from django.utils import timezone

from .models import Vehicle


SAMPLE_VEHICLES = [
    {
        'name': 'Toyota Corolla Axio',
        'model': 'Hybrid',
        'plate_number': 'KDR 210A',
        'vehicle_type': 'Sedan',
        'transmission': 'Automatic',
        'fuel_type': 'Petrol Hybrid',
        'seat_count': 5,
        'door_count': 4,
        'year': 2020,
        'mileage': 46000,
        'engine_size': '1.5L',
        'drive_type': 'FWD',
        'pickup_location': 'Nairobi, Kenya',
        'dropoff_location': 'Nairobi, Kenya',
        'rating': Decimal('4.5'),
        'review_count': 146,
        'price_per_day': Decimal('5500.00'),
        'status': 'Available',
        'is_featured': True,
        'image_url': 'https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Corolla%20Axio%20Hybrid%20%28NKE165%29%20front.JPG',
        'description': 'A practical Nairobi sedan with low running costs, easy parking, and the kind of fuel efficiency daily renters actually care about.',
    },
    {
        'name': 'Toyota Crown',
        'model': 'S220',
        'plate_number': 'KDR 211B',
        'vehicle_type': 'Sedan',
        'transmission': 'Automatic',
        'fuel_type': 'Petrol',
        'seat_count': 5,
        'door_count': 4,
        'year': 2019,
        'mileage': 38000,
        'engine_size': '2.5L',
        'drive_type': 'FWD',
        'pickup_location': 'Nairobi, Kenya',
        'dropoff_location': 'Nairobi, Kenya',
        'rating': Decimal('4.6'),
        'review_count': 112,
        'price_per_day': Decimal('9000.00'),
        'status': 'Available',
        'is_featured': True,
        'image_url': 'https://commons.wikimedia.org/wiki/Special:FilePath/TOYOTA%20CROWN%20%28S220%29.jpg',
        'description': 'An executive sedan suited to airport pickups, client meetings, and polished city travel with a quieter ride than the budget class.',
    },
    {
        'name': 'Nissan X-Trail',
        'model': '2.0 4WD',
        'plate_number': 'KDR 212C',
        'vehicle_type': 'SUV',
        'transmission': 'Automatic',
        'fuel_type': 'Petrol',
        'seat_count': 5,
        'door_count': 4,
        'year': 2021,
        'mileage': 32000,
        'engine_size': '2.0L',
        'drive_type': '4WD',
        'pickup_location': 'Nairobi, Kenya',
        'dropoff_location': 'Nairobi, Kenya',
        'rating': Decimal('4.6'),
        'review_count': 174,
        'price_per_day': Decimal('8000.00'),
        'status': 'Available',
        'is_featured': True,
        'image_url': 'https://commons.wikimedia.org/wiki/Special:FilePath/Nissan%20X-TRAIL%2020X%20%28DBA-T32%29%20front.jpg',
        'description': 'A solid mid-size SUV for family trips, Nairobi-to-Naivasha weekends, and travelers who want more space without Prado pricing.',
    },
    {
        'name': 'Toyota Harrier',
        'model': 'Hybrid Z',
        'plate_number': 'KDR 213D',
        'vehicle_type': 'SUV',
        'transmission': 'Automatic',
        'fuel_type': 'Petrol Hybrid',
        'seat_count': 5,
        'door_count': 4,
        'year': 2021,
        'mileage': 29000,
        'engine_size': '2.5L',
        'drive_type': 'AWD',
        'pickup_location': 'Nairobi, Kenya',
        'dropoff_location': 'Nairobi, Kenya',
        'rating': Decimal('4.7'),
        'review_count': 131,
        'price_per_day': Decimal('11000.00'),
        'status': 'Available',
        'is_featured': True,
        'image_url': 'https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20HARRIER%20HYBRID%20Z%202WD%20%28front%29.jpg',
        'description': 'A premium crossover popular with Nairobi self-drive customers who want a cleaner cabin, elevated ride height, and stronger road presence.',
    },
    {
        'name': 'Toyota Land Cruiser Prado',
        'model': 'TX150',
        'plate_number': 'KDR 214E',
        'vehicle_type': 'SUV',
        'transmission': 'Automatic',
        'fuel_type': 'Diesel',
        'seat_count': 7,
        'door_count': 4,
        'year': 2019,
        'mileage': 54000,
        'engine_size': '3.0L',
        'drive_type': '4WD',
        'pickup_location': 'Nairobi, Kenya',
        'dropoff_location': 'Nairobi, Kenya',
        'rating': Decimal('4.8'),
        'review_count': 208,
        'price_per_day': Decimal('15000.00'),
        'status': 'Available',
        'is_featured': False,
        'image_url': 'https://commons.wikimedia.org/wiki/Special:FilePath/2013-2017%20Toyota%20Land%20Cruiser%20Prado%20%28front%29.jpg',
        'description': 'A go-to safari and upcountry rental with seven seats, diesel torque, and the kind of durability clients expect for longer Kenyan routes.',
    },
    {
        'name': 'BMW X5',
        'model': 'xDrive35d',
        'plate_number': 'KDR 215F',
        'vehicle_type': 'SUV',
        'transmission': 'Automatic',
        'fuel_type': 'Diesel',
        'seat_count': 5,
        'door_count': 4,
        'year': 2022,
        'mileage': 24000,
        'engine_size': '3.0L',
        'drive_type': 'AWD',
        'pickup_location': 'Nairobi, Kenya',
        'dropoff_location': 'Nairobi, Kenya',
        'rating': Decimal('4.9'),
        'review_count': 96,
        'price_per_day': Decimal('30000.00'),
        'status': 'Available',
        'is_featured': False,
        'image_url': 'https://commons.wikimedia.org/wiki/Special:FilePath/BMW%20X5%20xDrive35d%20%28G05%29%20front.jpg',
        'description': 'A premium executive SUV for higher-end rentals, business travel, and customers who specifically want a luxury self-drive option in Nairobi.',
    },
]


def ensure_demo_vehicles():
    today = timezone.localdate()

    for index, vehicle_data in enumerate(SAMPLE_VEHICLES):
        payload = vehicle_data.copy()
        if payload['status'] != 'Available':
            payload['next_available_date'] = today + timedelta(days=5 + index)
        else:
            payload['next_available_date'] = None
        payload['image'] = None
        Vehicle.objects.update_or_create(
            plate_number=payload['plate_number'],
            defaults=payload,
        )
