# Generated by Django 6.0.4 on 2026-05-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_vehicle_next_available_date_customer_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropoff_location',
            field=models.CharField(blank=True, default='Nairobi, Kenya', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, default='Nairobi, Kenya', max_length=120),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='door_count',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='dropoff_location',
            field=models.CharField(blank=True, default='Nairobi, Kenya', max_length=120),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_size',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, default='Petrol', max_length=40),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pickup_location',
            field=models.CharField(blank=True, default='Nairobi, Kenya', max_length=120),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='review_count',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seat_count',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, default='Automatic', max_length=40),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Rented', 'Rented'), ('Returned', 'Returned'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
    ]
